name: Publish package to GitHub Packages
on:
  push:
    branches: [ "main" ]  # Only publish from main branch
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: 'github'
      - run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging 
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
